services:
  db:
    image: postgres:17-alpine
    container_name: db
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - shop_db:/var/lib/postgresql/data

volumes:
  shop_db: