services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    container_name: shop_db
    environment:
      POSTGRES_DB: ${APP_DB_DATABASE}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - ${APP_DB_PORT}:5432
    volumes:
      - shop_db:/var/lib/postgresql/data

volumes:
  shop_db: